### ISSUE TITLE
Error creating note: File name cannot contain special characters

### ISSUE THREAD

**Issue by malleVF** [monnierant/obsidian-simple-rss#7] opened 2023-08-06 17:17 UTC
Creating note in obsidian cannot allow the following characters:
\* " \ / < > : | ?

Would be great to remove such characters before file creation.

**Comment by monnierant** [comment] 2023-08-06 22:48
good idea i will add this filter un the next version in few days/weeks when i get back from hollidays

**Comment by monnierant** [comment] 2023-08-14 14:20
On my test, the issue is solve. Please let me know if you still enconter the issue after updating to 0.1.6 by reopening this issue

**Comment by marienvo** [comment] 2023-11-12 15:43
A hash (#) can still be in the title. No problem for my file system it seems, but Obsidian and Dataview do not seem to like files with hashes in the filename. Maybe this can be fixed as well? For now I'm using guid as the filename for a specific feed, but not very pretty.

Also: some RSS feeds have spaces at the beginning of some of there titles. Would be nice if those were trimmed as well (doesn't occur often, but still 😅)

Very nice plugin btw! 😄🎉

**Comment by monnierant** [comment] 2023-11-12 18:47
I will reopen the issue then to add your recommandation.

Got lot of work those days so the patch took a bit of time but i will add those changes into it.

**Comment by monnierant** [comment] 2024-01-20 21:03
The # char have been sanitize from titles and is not more kept in file names. I can't test it as i have not found a rss feed with # in it. I will close the issue as the feature is in the last release https://github.com/monnierant/obsidian-simple-rss/releases/tag/0.3.11

**Closed as completed by monnierant** 2024-01-20 21:03 UTC
